/-
Copyright (c) 2026 Aditya Rao. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Mathlib
import KrohnRhodes.Foundations.WreathProduct
import KrohnRhodes.Foundations.LocalDivisor
import KrohnRhodes.Foundations.ConstantMaps
import KrohnRhodes.Foundations.Division
import KrohnRhodes.Foundations.GreenRelations
import KrohnRhodes.Foundations.MonoidWreathBridge
import KrohnRhodes.Foundations.KrasnerKaloujnine
import KrohnRhodes.FactorTower

/-!
# The Krohn–Rhodes prime decomposition theorem

`krohn_rhodes_prime_decomposition`: every finite monoid `M` admits a `KRFactorTowerGrp M` — an
explicit list of factors, each a finite aperiodic monoid or a finite simple group, such that `M`
divides their right-iterated wreath product and every simple-group factor divides `M`.

The proof follows V. Diekert, M. Kufleitner, B. Steinberg, *The Krohn–Rhodes Theorem and Local
Divisors*, Fundamenta Informaticae 116 (2012), arXiv:1111.1585 (Theorem 3.1, Corollary 3.2,
Theorem 4.1), written for left actions: `Function.End Q` multiplies by composition,
`(f * g) x = f (g x)`.

All statements are for types in `Type` (universe 0).
-/

namespace KrohnRhodes

open Green

/-- The full transformation monoid of a finite type is finite. `Function.End Q` is
definitionally `Q → Q`, but the `Pi.finite` instance does not fire through the semireducible
`Function.End`, and Mathlib v4.28 does not provide this instance. Needed so that statements about
`DivTowerWreath ↥(closureMonoid act) …` elaborate. `Finite` is a `Prop`, so the instance cannot
create diamonds. -/
instance instFiniteFunctionEnd (Q : Type) [Finite Q] : Finite (Function.End Q) :=
  inferInstanceAs (Finite (Q → Q))

/-! ## The reset submonoid (constants with identity)

Convention: `Function.End Q` multiplies by composition `(f * g) x = f (g x)`, so the constant
maps `constEnd q` are LEFT zeros (`constEnd p * t = constEnd p`,
`t * constEnd q = constEnd (t q)`). The reset submonoid is the left-action counterpart of the
reset monoid `U_X = X̄ ∪ {1}` of DKS §2.4. -/

/-- **The reset submonoid of the full transformation monoid.** For a type $Q$, the *reset
submonoid* of the full transformation monoid $\mathrm{End}(Q)$ (multiplication is composition,
$(f \cdot g)(x) = f(g(x))$) is the submonoid generated by the constant maps $\overline{q}$ (Lean:
`constEnd`), $q \in Q$. Constant maps are *left* zeros ($\overline{p} \cdot t = \overline{p}$ and
$t \cdot \overline{q} = \overline{t(q)}$), so the generated carrier collapses to
$\{1\} \cup \{\overline{q} \mid q \in Q\}$ (`mem_reset_submonoid`). This is the left-action
counterpart of the reset monoid $U_X = \bar{X} \cup \{1\}$ of DKS (arXiv:1111.1585) §2.4 — right
zeros there, left zeros here, the flip forced by the composition order. It is defined as a
`Submonoid.closure` of the generators rather than by its explicit carrier, so the definition
carries no closedness obligations; the carrier description is the separate `mem_reset_submonoid`. -/
def resetSubmonoid (Q : Type) : Submonoid (Function.End Q) :=
  Submonoid.closure (Set.range (constEnd : Q → Function.End Q))

/-- **Membership in the reset submonoid: identity or constant.** For every transformation
$t \in \mathrm{End}(Q)$ of a type $Q$: $t$ lies in the reset submonoid `resetSubmonoid` if and
only if $t = 1$ or $t$ is a constant map (the predicate `IsConstEnd`:
$\exists q,\ t = \overline{q}$).

*Proof sketch.* Right-to-left: $1$ belongs to every submonoid, and every constant map is a
generator (`Submonoid.subset_closure`). Left-to-right: induction over the submonoid closure
(`Submonoid.closure_induction`): a generator is a constant (`isConstEnd_constEnd`); $1$ is the
left disjunct; and for a product $x \cdot y$ with both factors identity-or-constant, either
$x = 1$ — then the product is $y$ and the inductive hypothesis for $y$ applies — or
$x = \overline{p}$ is constant and absorbs $y$ on the left by the left-zero law
(`constEnd_mul`: $\overline{p} \cdot y = \overline{p}$), so the product
is again a constant. This is the closure computation of DKS §2.4. -/
lemma mem_reset_submonoid (Q : Type) (t : Function.End Q) :
    t ∈ resetSubmonoid Q ↔ t = 1 ∨ IsConstEnd t := by
  constructor
  · intro ht
    induction ht using Submonoid.closure_induction with
    | mem x hx =>
      obtain ⟨q, rfl⟩ := hx
      exact Or.inr (isConstEnd_constEnd q)
    | one => exact Or.inl rfl
    | mul x y _ _ ihx ihy =>
      rcases ihx with rfl | ⟨p, rfl⟩
      · rw [one_mul]; exact ihy
      · exact Or.inr ⟨p, constEnd_mul p y⟩
  · rintro (rfl | ⟨q, rfl⟩)
    · exact one_mem _
    · exact Submonoid.subset_closure ⟨q, rfl⟩

/-- **The reset submonoid is aperiodic.** Every element of the reset submonoid `resetSubmonoid`
of $\mathrm{End}(Q)$, viewed as a finite monoid in its own right, is aperiodic in the sense of
Green's relations (`Green.IsAperiodicElem`): its $\mathcal{H}$-class inside the submonoid is
trivial — $a \mathrel{\mathcal{H}} b$ implies $a = b$. This witnesses the reset factor of the
decomposition as a genuine aperiodic Krohn-Rhodes atom (DKS §2.4: the reset monoid is aperiodic).

*Proof sketch.* By `mem_reset_submonoid` every member of the submonoid is the identity or a
constant, so `isAperiodicElem_of_id_or_const` applies; its conclusion
is exactly the $\mathcal{H}$-triviality shape obtained by unfolding `Green.H` (an
$\mathcal{L}$-witness pair and an $\mathcal{R}$-witness pair in the subtype monoid) — destructure
the $\mathcal{H}$ hypothesis and apply. -/
lemma reset_submonoid_aperiodic (Q : Type) :
    ∀ a : ↥(resetSubmonoid Q), IsAperiodicElem a := by
  intro a b hab
  exact isAperiodicElem_of_id_or_const (resetSubmonoid Q)
    (fun t ht => (mem_reset_submonoid Q t).mp ht) a b ⟨hab.1, hab.2⟩

/-! ## The constants closure of an action -/

/-- **The constants closure of a transformation representation.** For a monoid homomorphism
$\mathrm{act} \colon M \to^* \mathrm{End}(Q)$, the *constants closure* is the submonoid of
$\mathrm{End}(Q)$ generated by the image of $\mathrm{act}$ together with all constant maps
$\overline{q}$. This is the counterpart of the closure $\overline{(X,M)} = (X, M \cup \bar{X})$
of DKS §2.4. DKS define the closure by its explicit carrier $M \cup \bar{X}$ and verify
closedness by a four-case product computation; here it is a `Submonoid.closure`, so that
computation is not a separate proof obligation — the only facts used later are generation over a
generating set of $M$ (`closure_monoid_gen`) and the division `sgdiv_closure_monoid`. The whole
DKS induction runs on closures: it produces towers for $\overline{(Q,M)}$, and the main theorem
recovers $M$ through `sgdiv_closure_monoid`. -/
def closureMonoid {M Q : Type} [Monoid M] (act : M →* Function.End Q) :
    Submonoid (Function.End Q) :=
  Submonoid.closure (Set.range (⇑act) ∪ Set.range (constEnd : Q → Function.End Q))

/-- **A faithfully represented monoid divides its constants closure.** Let $M$ be a monoid and
$\mathrm{act} \colon M \to^* \mathrm{End}(Q)$ an injective monoid homomorphism. Then $M$ divides
the constants closure `closureMonoid` as a semigroup (`SgDiv`: some subsemigroup of
$\overline{(Q,M)}$ maps onto $M$ by a multiplicative surjection). Used once, in the master
assembly `krohn_rhodes_prime_decomposition`, to pull the tower of the closure back to $M$.

*Proof sketch.* The image of $\mathrm{act}$ is contained in the closure (left disjunct of the
generating set, `Submonoid.subset_closure`), so $\mathrm{act}$ corestricts to a monoid
homomorphism $M \to^* \overline{(Q,M)}$ (`MonoidHom.codRestrict`), injective because
$\mathrm{act}$ is. `sgDiv_of_injective_monoidHom` turns an injective
monoid homomorphism into a semigroup division. -/
lemma sgdiv_closure_monoid {M Q : Type} [Monoid M] (act : M →* Function.End Q)
    (hf : Function.Injective act) : SgDiv M ↥(closureMonoid act) := by
  have hmem : ∀ m : M, act m ∈ closureMonoid act := fun m =>
    Submonoid.subset_closure (Set.mem_union_left _ ⟨m, rfl⟩)
  refine KrohnRhodes.sgDiv_of_injective_monoidHom
    (MonoidHom.codRestrict act (closureMonoid act) hmem) ?_
  intro a b hab
  exact hf (congrArg Subtype.val hab)

/-- **A generating set of the monoid generates its constants closure.** Let
$\mathrm{act} \colon M \to^* \mathrm{End}(Q)$ be a monoid homomorphism and $A \subseteq M$ a
generating set of $M$ ($\texttt{Submonoid.closure}\,A = \top$). Then the submonoid of
$\mathrm{End}(Q)$ generated by $\mathrm{act}(A) \cup \{\overline{q} \mid q\}$ equals the
constants closure `closureMonoid`. This is what lets the covering argument of
`main_decomposition` check covers on the generators $\mathrm{act}(a)$, $a \in A$, only.

*Proof sketch.* Both sides split along the union (`Submonoid.closure_union`) with identical
constants summand, so it suffices to identify the other summands with the range submonoid of
$\mathrm{act}$: $\langle \mathrm{act}(A) \rangle = \mathrm{act}(\langle A \rangle) =
\mathrm{act}(\top) = \mathrm{mrange} (\mathrm{act})$ — the image of a closure is the closure of
the image (`MonoidHom.map_mclosure`), then the hypothesis $\langle A \rangle = \top$ and
`MonoidHom.mrange_eq_map`; and
$\langle \mathrm{range}(\mathrm{act}) \rangle = \mathrm{mrange}(\mathrm{act})$ because the range
is already a submonoid (`Submonoid.closure_eq` at the carrier identification
`MonoidHom.coe_mrange`). Pure closure algebra — no closure induction is needed,
$\mathrm{act}(1) = 1$ and multiplicativity being absorbed into `map_mclosure`. -/
lemma closure_monoid_gen {M Q : Type} [Monoid M] (act : M →* Function.End Q)
    (A : Set M) (hA : Submonoid.closure A = ⊤) :
    Submonoid.closure ((⇑act) '' A ∪ Set.range (constEnd : Q → Function.End Q)) =
      closureMonoid act := by
  have h1 : Submonoid.closure ((⇑act) '' A) = MonoidHom.mrange act := by
    rw [← MonoidHom.map_mclosure, hA, ← MonoidHom.mrange_eq_map]
  have h2 : Submonoid.closure (Set.range ⇑act) = MonoidHom.mrange act := by
    rw [← MonoidHom.coe_mrange, Submonoid.closure_eq]
  rw [closureMonoid, Submonoid.closure_union, Submonoid.closure_union, h1, h2]

/-! ## Covers and division from covering (DKS §2.3, Prop 2.3)

The evaluation wreath action used throughout is `w • (p, y) = (w.func y • p, w.base • y)`, the
action `WreathAssoc.actW` of `KrohnRhodes/FactorTower.lean`; the `Covers` predicate
inlines it, so no new `MulAction` instance is introduced. -/

/-- **The cover relation between wreath elements and transformations.** Fix monoids $A, B$, an
$A$-set $P$, a $B$-set $X$, a type $R$, and a map $\varphi \colon P \times X \to R$. An element
$w$ of the wreath product $A \wr_X B$ (multiplication
$(f_1,b_1)(f_2,b_2) = (x \mapsto f_1(b_2 \cdot x) f_2(x),\ b_1 b_2)$) *covers* a transformation
$t \in \mathrm{End}(R)$ when $\varphi(w \bullet s) = t(\varphi(s))$ for every $s \in P \times X$,
where $w \bullet (p, y) = (w.\mathrm{func}(y) \cdot p,\ w.\mathrm{base} \cdot y)$ is the
evaluation wreath action (`WreathAssoc.actW`; the definition inlines it). This is DKS §2.3; with
left actions, covers compose covariantly, with no order reversal. -/
def Covers {A B P X R : Type} [Monoid A] [Monoid B] [MulAction A P] [MulAction B X]
    (φ : P × X → R) (w : WreathProduct A B X) (t : Function.End R) : Prop :=
  ∀ (p : P) (y : X), φ (w.func y • p, w.base • y) = t (φ (p, y))

/-- **The identity wreath element covers the identity transformation.** In the setting of
`Covers`, the identity of the wreath product $A \wr_X B$ covers the identity of
$\mathrm{End}(R)$: $\varphi(1 \bullet s) = \varphi(s)$ for all $s$.

*Proof sketch.* Immediate: the identity wreath element has trivial decoration and base
(`WreathProduct.one_func`, `one_base`), and $1 \cdot p = p$, $1 \cdot y = y$ (`one_smul`). -/
lemma covers_one {A B P X R : Type} [Monoid A] [Monoid B] [MulAction A P] [MulAction B X]
    (φ : P × X → R) :
    Covers φ (1 : WreathProduct A B X) (1 : Function.End R) := by
  intro p y
  simp only [WreathProduct.one_func, WreathProduct.one_base, one_smul]
  rfl

/-- **Covers compose: a product of covers covers the product.** In the setting of `Covers`: if
$w_1$ covers $t_1$ and $w_2$ covers $t_2$, then $w_1 w_2$ covers $t_1 t_2$ (composition in
$\mathrm{End}(R)$, i.e. $(t_1 t_2)(r) = t_1(t_2(r))$). This is DKS Prop 2.3(1); with left actions
the orders align without reversal.

*Proof sketch.* $\varphi((w_1 w_2) \bullet s) = \varphi(w_1 \bullet (w_2 \bullet s))$ by the
wreath action law ($(w_1 w_2) \bullet s = w_1 \bullet (w_2 \bullet s)$, computed from
`WreathProduct.mul_func`/`mul_base` and `mul_smul` — the `mul_smul` field of `WreathAssoc.actW`);
this equals $t_1(\varphi(w_2 \bullet s)) = t_1(t_2(\varphi(s)))$ by the two cover hypotheses. -/
lemma covers_mul {A B P X R : Type} [Monoid A] [Monoid B] [MulAction A P] [MulAction B X]
    (φ : P × X → R) {w₁ w₂ : WreathProduct A B X} {t₁ t₂ : Function.End R}
    (h₁ : Covers φ w₁ t₁) (h₂ : Covers φ w₂ t₂) :
    Covers φ (w₁ * w₂) (t₁ * t₂) := by
  intro p y
  calc φ ((w₁ * w₂).func y • p, (w₁ * w₂).base • y)
      = φ (w₁.func (w₂.base • y) • (w₂.func y • p), w₁.base • (w₂.base • y)) := by
        rw [WreathProduct.mul_func, WreathProduct.mul_base, mul_smul, mul_smul]
    _ = t₁ (φ (w₂.func y • p, w₂.base • y)) := h₁ (w₂.func y • p) (w₂.base • y)
    _ = t₁ (t₂ (φ (p, y))) := congrArg t₁ (h₂ p y)
    _ = (t₁ * t₂) (φ (p, y)) := rfl

/-- **A wreath element covers at most one transformation (surjective decoding).** In the setting
of `Covers`, assume $\varphi$ is surjective. If $w$ covers both $t_1$ and $t_2$, then $t_1 = t_2$
(DKS Prop 2.3(2)). This is what makes the decoded transformation of a covering wreath element
well-defined in `sgdiv_of_covering`.

*Proof sketch.* For every $r \in R$ pick $s$ with $\varphi(s) = r$ (surjectivity); then
$t_1(r) = \varphi(w \bullet s) = t_2(r)$, and transformations agreeing pointwise are equal
(`funext`). -/
lemma covers_unique {A B P X R : Type} [Monoid A] [Monoid B] [MulAction A P] [MulAction B X]
    {φ : P × X → R} (hφ : Function.Surjective φ) {w : WreathProduct A B X}
    {t₁ t₂ : Function.End R} (h₁ : Covers φ w t₁) (h₂ : Covers φ w t₂) :
    t₁ = t₂ := by
  funext r
  obtain ⟨⟨p, y⟩, rfl⟩ := hφ r
  exact (h₁ p y).symm.trans (h₂ p y)

/-- **Division from covering: covered generators yield a wreath divisor.** In the setting of
`Covers`, let $\varphi \colon P \times X \to R$ be surjective, let $T$ be a submonoid of
$\mathrm{End}(R)$, and let $S \subseteq \mathrm{End}(R)$ generate $T$
($\texttt{Submonoid.closure}\,S = T$). If every $t \in S$ is covered by some $w \in A \wr_X B$,
then $T$ divides $A \wr_X B$ as a semigroup (`SgDiv`). This is the division-from-covering
argument of DKS §2.3.

*Proof sketch.* First, every $t \in T = \langle S \rangle$ is covered by some wreath element: by
induction over the closure representation (`Submonoid.closure_induction`), generators are covered
by hypothesis, $1$ is covered by `covers_one`, and products of covered elements are covered by
`covers_mul`. Let $V := \{w \mid \exists t \in T,\ w \text{ covers } t\}$: it is closed under
products by `covers_mul` (the covered transformations multiply inside the submonoid $T$), so $V$
is a subsemigroup of the wreath. Define $\psi \colon V \to T$ sending $w$ to THE transformation
it covers: well-defined by `covers_unique` (with surjectivity of $\varphi$) plus choice, and
multiplicative by `covers_mul` together with `covers_unique` (both sides of the multiplicativity
equation cover the same product element). $\psi$ is surjective onto $T$: a $t \in T$ is covered
by some $w$ by the first step, $w \in V$, and the decoded transformation of $w$ is $t$ by
`covers_unique`. -/
lemma sgdiv_of_covering {A B P X R : Type} [Monoid A] [Monoid B] [MulAction A P]
    [MulAction B X] {φ : P × X → R} (_hφ : Function.Surjective φ)
    (S : Set (Function.End R)) (T : Submonoid (Function.End R))
    (_hgen : Submonoid.closure S = T)
    (_hcov : ∀ t ∈ S, ∃ w : WreathProduct A B X, Covers φ w t) :
    SgDiv ↥T (WreathProduct A B X) := by
  classical
  -- Step 1: every element of `T = ⟨S⟩` is covered by some wreath element.
  have hcovT : ∀ t ∈ T, ∃ w : WreathProduct A B X, Covers φ w t := by
    intro t ht
    rw [← _hgen] at ht
    induction ht using Submonoid.closure_induction with
    | mem x hx => exact _hcov x hx
    | one => exact ⟨1, covers_one φ⟩
    | mul x y _ _ ihx ihy =>
      obtain ⟨wx, hwx⟩ := ihx
      obtain ⟨wy, hwy⟩ := ihy
      exact ⟨wx * wy, covers_mul φ hwx hwy⟩
  -- Step 2: the subsemigroup `V` of wreath elements covering some member of `T`.
  let V : Subsemigroup (WreathProduct A B X) :=
    { carrier := {w : WreathProduct A B X | ∃ t ∈ T, Covers φ w t}
      mul_mem' := by
        rintro w₁ w₂ ⟨t₁, ht₁, hc₁⟩ ⟨t₂, ht₂, hc₂⟩
        exact ⟨t₁ * t₂, mul_mem ht₁ ht₂, covers_mul φ hc₁ hc₂⟩ }
  -- Step 3: the decoded transformation of a member of `V` (choice; unique by
  -- `covers_unique` since `φ` is surjective).
  have hmem : ∀ w : ↥V, ∃ t ∈ T, Covers φ (w : WreathProduct A B X) t := fun w => w.2
  have hdecC : ∀ w : ↥V,
      Covers φ (w : WreathProduct A B X) (Classical.choose (hmem w)) :=
    fun w => (Classical.choose_spec (hmem w)).2
  refine ⟨V,
    ⟨fun w => ⟨Classical.choose (hmem w), (Classical.choose_spec (hmem w)).1⟩, ?_⟩, ?_⟩
  · -- Multiplicativity: both sides cover `↑w₁ * ↑w₂`, so they agree by uniqueness.
    intro w₁ w₂
    exact Subtype.ext (covers_unique _hφ (hdecC (w₁ * w₂))
      (covers_mul φ (hdecC w₁) (hdecC w₂)))
  · -- Surjectivity: a `t ∈ T` is covered by some `w` (Step 1); `w ∈ V`, and the decoded
    -- transformation of `w` is `t` by uniqueness.
    rintro ⟨t, ht⟩
    obtain ⟨w, hw⟩ := hcovT t ht
    have hwV : w ∈ V := ⟨t, ht, hw⟩
    exact ⟨⟨w, hwV⟩, Subtype.ext (covers_unique _hφ (hdecC ⟨w, hwV⟩) hw)⟩

/-! ## The local divisor and its action on the image state set

The local divisor `KrohnRhodes.LocalDivisor M c` (carrier `cM ∩ Mc`, twisted
product, identity `c`, and the division `localDivides : M_c ÷ M`) is defined in
`KrohnRhodes/Foundations/LocalDivisor.lean`; DKS §2.5 allows the `cM ∩ Mc` variant. This
section adds the cardinality drop for a non-unit `c` and the faithful action of `M_c` on the
image state set `cQ`. -/

/-- **The local divisor at a non-unit is strictly smaller.** Let $M$ be a finite monoid and
$c \in M$ a non-unit. Then $|M_c| < |M|$, where $M_c$ is the local divisor
`LocalDivisor` $M$ $c$ (carrier $cM \cap Mc$). Cardinalities are
`Nat.card`; both sides are finite. (DKS §2.5: if $c$ is not a unit then $1 \notin cM \cap Mc$.)

*Proof sketch.* Pure algebra, no finiteness in the key step: if $1 = c a$ and $1 = b c$ then
$b = b(ca) = (bc)a = a$, so $a$ is a two-sided inverse of $c$ ($ca = 1$ and $ac = 1$) and $c$ is
a unit — contradiction. Hence no element of $M_c$ has value $1$: the value map
$M_c \hookrightarrow M$ (injective by `LocalDivisor.ext`) misses the point $1$. Transporting both
cardinalities through `Fintype.ofFinite` and `Nat.card_eq_fintype_card`, the
injection-missing-a-point counting lemma `Fintype.card_lt_of_injective_of_notMem` gives the
strict inequality. -/
lemma local_divisor_card_lt {M : Type} [Monoid M] [Finite M] {c : M} (hc : ¬ IsUnit c) :
    Nat.card (LocalDivisor M c) < Nat.card M := by
  have hone : ∀ x : LocalDivisor M c, x.val ≠ 1 := by
    intro x hx
    obtain ⟨a, ha⟩ := x.mem_left
    obtain ⟨b, hb⟩ := x.mem_right
    have h1 : c * a = 1 := by rw [← ha]; exact hx
    have h2 : b * c = 1 := by rw [← hb]; exact hx
    have h3 : a * c = 1 := by
      have hba : b = a := by
        calc b = b * (c * a) := by rw [h1, mul_one]
          _ = b * c * a := by rw [mul_assoc]
          _ = a := by rw [h2, one_mul]
      rw [← hba]; exact h2
    exact hc ⟨⟨c, a, h1, h3⟩, rfl⟩
  haveI : Fintype M := Fintype.ofFinite M
  haveI : Fintype (LocalDivisor M c) := Fintype.ofFinite _
  rw [Nat.card_eq_fintype_card, Nat.card_eq_fintype_card]
  refine Fintype.card_lt_of_injective_of_notMem (LocalDivisor.val (c := c))
    (fun _ _ h => LocalDivisor.ext h) (b := 1) ?_
  rintro ⟨x, hx⟩
  exact hone x hx

/-- **The image state set of the chosen non-unit.** For a monoid homomorphism
$\mathrm{act} \colon M \to^* \mathrm{End}(Q)$ and $c \in M$, the *image state set* $cQ$ is the
subtype $\{q \in Q \mid \exists x,\ q = \mathrm{act}(c)(x)\}$ — the set of states in the image of
the transformation induced by $c$. This is the state set on which the local divisor $M_c$ acts
(DKS Lemma 2.11). -/
def cQSet {M Q : Type} [Monoid M] (act : M →* Function.End Q) (c : M) : Type :=
  {q : Q // ∃ x : Q, q = act c x}

/-- **The action of the local divisor on the image state set.** For
$\mathrm{act} \colon M \to^* \mathrm{End}(Q)$ and $c \in M$, the monoid homomorphism
$M_c \to^* \mathrm{End}(cQ)$: an element $u \in cM \cap Mc$ with chosen factorization $u = b c$
(the `Classical.choose` of `LocalDivisor.mem_right`) acts on $p \in cQ$ by
$p \mapsto \mathrm{act}(b)(p)$. Well-definedness (the obligations embedded in this definition,
following DKS Lemma 2.11 with the $Mc$-witness — left actions force the $Mc$-side where DKS use
$cM$): (i) the value lands in $cQ$ — for $p = \mathrm{act}(c)(x)$,
$\mathrm{act}(b)(p) = \mathrm{act}(bc)(x) = \mathrm{act}(u)(x)$, and writing $u = c a$ (left
membership) this is $\mathrm{act}(c)(\mathrm{act}(a)(x)) \in cQ$; (ii) the displayed formula
$\mathrm{act}(u)(x)$ depends only on $u$, not on the chosen $b$; (iii) the identity $c = 1_{M_c}$
acts as the identity, and the twisted product acts by composition — both computed from
$\mathrm{act}(u)(x)$-normal forms via `LocalDivisor.mul_val`. Faithfulness is the separate
`local_act_injective`. -/
noncomputable def localActHom {M Q : Type} [Monoid M] (act : M →* Function.End Q) (c : M) :
    LocalDivisor M c →* Function.End (cQSet act c) where
  toFun u := fun p =>
    ⟨act (Classical.choose u.mem_right) p.1, by
      obtain ⟨x, hx⟩ := p.2
      obtain ⟨a, ha⟩ := u.mem_left
      refine ⟨act a x, ?_⟩
      have hb := Classical.choose_spec u.mem_right
      rw [hx]
      calc act (Classical.choose u.mem_right) (act c x)
          = act (Classical.choose u.mem_right * c) x := by rw [map_mul]; rfl
        _ = act u.val x := by rw [← hb]
        _ = act (c * a) x := by rw [← ha]
        _ = act c (act a x) := by rw [map_mul]; rfl⟩
  map_one' := by
    funext p
    apply Subtype.ext
    obtain ⟨x, hx⟩ := p.2
    have hcb : c = Classical.choose (1 : LocalDivisor M c).mem_right * c :=
      (LocalDivisor.one_val).symm.trans
        (Classical.choose_spec (1 : LocalDivisor M c).mem_right)
    change act (Classical.choose (1 : LocalDivisor M c).mem_right) p.1 = p.1
    rw [hx]
    calc act (Classical.choose (1 : LocalDivisor M c).mem_right) (act c x)
        = act (Classical.choose (1 : LocalDivisor M c).mem_right * c) x := by
          rw [map_mul]; rfl
      _ = act c x := by rw [← hcb]
  map_mul' := by
    intro u v
    funext p
    apply Subtype.ext
    obtain ⟨x, hx⟩ := p.2
    have hbu := Classical.choose_spec u.mem_right
    have hbv := Classical.choose_spec v.mem_right
    have hbuv := Classical.choose_spec (u * v).mem_right
    have hv0 := Classical.choose_spec v.mem_left
    change act (Classical.choose (u * v).mem_right) p.1
        = act (Classical.choose u.mem_right) (act (Classical.choose v.mem_right) p.1)
    rw [hx]
    have lhs : act (Classical.choose (u * v).mem_right) (act c x)
        = act (u.val * Classical.choose v.mem_left) x := by
      calc act (Classical.choose (u * v).mem_right) (act c x)
          = act (Classical.choose (u * v).mem_right * c) x := by rw [map_mul]; rfl
        _ = act ((u * v).val) x := by rw [← hbuv]
        _ = act (u.val * Classical.choose v.mem_left) x := by rw [LocalDivisor.mul_val]
    have rhs : act (Classical.choose u.mem_right)
          (act (Classical.choose v.mem_right) (act c x))
        = act (u.val * Classical.choose v.mem_left) x := by
      calc act (Classical.choose u.mem_right)
            (act (Classical.choose v.mem_right) (act c x))
          = act (Classical.choose u.mem_right)
              (act (Classical.choose v.mem_right * c) x) := by rw [map_mul]; rfl
        _ = act (Classical.choose u.mem_right) (act v.val x) := by rw [← hbv]
        _ = act (Classical.choose u.mem_right)
              (act (c * Classical.choose v.mem_left) x) := by rw [← hv0]
        _ = act (Classical.choose u.mem_right)
              (act c (act (Classical.choose v.mem_left) x)) := by rw [map_mul]; rfl
        _ = act (Classical.choose u.mem_right * c)
              (act (Classical.choose v.mem_left) x) := by rw [map_mul]; rfl
        _ = act u.val (act (Classical.choose v.mem_left) x) := by rw [← hbu]
        _ = act (u.val * Classical.choose v.mem_left) x := by rw [map_mul]; rfl
    rw [lhs, rhs]

/-- **The local divisor acts faithfully on the image state set.** If
$\mathrm{act} \colon M \to^* \mathrm{End}(Q)$ is injective, then the local-divisor action
`localActHom` is injective: distinct elements of $M_c$ induce distinct transformations of $cQ$.
This is the faithfulness half of DKS Lemma 2.11, supplying the injectivity hypothesis when the
induction `dks_aux` recurses into $(cQ, M_c)$.

*Proof sketch.* Suppose $u, v \in M_c$ act identically on $cQ$. For every $x \in Q$ the point
$\mathrm{act}(c)(x)$ lies in $cQ$, and the displayed well-definedness formula of `localActHom`
gives $\mathrm{act}(u)(x) = u \bullet (\mathrm{act}(c)(x)) = v \bullet (\mathrm{act}(c)(x)) =
\mathrm{act}(v)(x)$ (values through `LocalDivisor.val`); hence
$\mathrm{act}(u.\mathrm{val}) = \mathrm{act}(v.\mathrm{val})$ as transformations, so
$u.\mathrm{val} = v.\mathrm{val}$ by injectivity of $\mathrm{act}$, so $u = v$
(`LocalDivisor.ext`). -/
lemma local_act_injective {M Q : Type} [Monoid M] (act : M →* Function.End Q) (c : M)
    (hf : Function.Injective act) : Function.Injective (localActHom act c) := by
  intro u v huv
  apply LocalDivisor.ext
  apply hf
  funext x
  have h : localActHom act c u ⟨act c x, x, rfl⟩ = localActHom act c v ⟨act c x, x, rfl⟩ :=
    congrFun huv ⟨act c x, x, rfl⟩
  have h1 : act (Classical.choose u.mem_right) (act c x)
      = act (Classical.choose v.mem_right) (act c x) := congrArg Subtype.val h
  have hu := Classical.choose_spec u.mem_right
  have hv := Classical.choose_spec v.mem_right
  calc act u.val x
      = act (Classical.choose u.mem_right * c) x := by rw [← hu]
    _ = act (Classical.choose u.mem_right) (act c x) := by rw [map_mul]; rfl
    _ = act (Classical.choose v.mem_right) (act c x) := h1
    _ = act (Classical.choose v.mem_right * c) x := by rw [map_mul]; rfl
    _ = act v.val x := by rw [← hv]

/-! ## The main decomposition (DKS Theorem 3.1) -/

/-- **The extension action of a submonoid on states plus carrier.** For
$\mathrm{act} \colon M \to^* \mathrm{End}(Q)$ and a submonoid $N \le M$, the monoid homomorphism
$N \to^* \mathrm{End}(Q \sqcup N)$: $n$ sends $\mathrm{inl}\,q$ to
$\mathrm{inl}\,(\mathrm{act}(n)(q))$ and $\mathrm{inr}\,m$ to $\mathrm{inr}\,(n m)$ (left
multiplication in $N$). This is the base coordinate $X' = Q \sqcup N$ of DKS Thm 3.1 (their
$X \cup N$, with $N$ acting on itself on the left). The embedded obligations (identity and
multiplicativity) are the case computations $\mathrm{act}(1) = 1$, $1 \cdot m = m$,
$\mathrm{act}(n_1 n_2) = \mathrm{act}(n_1)\mathrm{act}(n_2)$, and associativity of
multiplication. Injectivity is the separate `ext_act_injective`. -/
def extAct {M Q : Type} [Monoid M] (act : M →* Function.End Q) (N : Submonoid M) :
    ↥N →* Function.End (Q ⊕ ↥N) where
  toFun n := fun s =>
    Sum.elim (fun q => Sum.inl (act n.1 q)) (fun m => Sum.inr (n * m)) s
  map_one' := by
    funext s
    cases s with
    | inl q =>
        change Sum.inl (act ((1 : ↥N) : M) q) = _
        rw [OneMemClass.coe_one, map_one]
        rfl
    | inr m =>
        change Sum.inr ((1 : ↥N) * m) = _
        rw [one_mul]
        rfl
  map_mul' := by
    intro n₁ n₂
    funext s
    cases s with
    | inl q =>
        change Sum.inl (act ((n₁ * n₂ : ↥N) : M) q)
            = Sum.inl (act (n₁ : M) (act (n₂ : M) q))
        rw [MulMemClass.coe_mul, map_mul]
        rfl
    | inr m =>
        change Sum.inr (n₁ * n₂ * m) = Sum.inr (n₁ * (n₂ * m))
        rw [mul_assoc]

/-- **The extension action is faithful.** For every monoid homomorphism
$\mathrm{act} \colon M \to^* \mathrm{End}(Q)$ and submonoid $N \le M$, the extension action
`extAct` is injective — with NO faithfulness hypothesis on $\mathrm{act}$: the $\mathrm{inr}$
component alone separates elements (evaluate at $\mathrm{inr}\,1$). Supplies the injectivity
hypothesis when the induction `dks_aux` recurses into $(Q \sqcup N, N)$.

*Proof sketch.* If $n_1, n_2 \in N$ induce the same transformation of $Q \sqcup N$, evaluate at
$\mathrm{inr}\,1$: $\mathrm{inr}\,(n_1 \cdot 1) = \mathrm{inr}\,(n_2 \cdot 1)$, so $n_1 = n_2$ by
injectivity of $\mathrm{inr}$ and `mul_one`. -/
lemma ext_act_injective {M Q : Type} [Monoid M] (act : M →* Function.End Q)
    (N : Submonoid M) : Function.Injective (extAct act N) := by
  intro n₁ n₂ h
  have h2 : (Sum.inr (n₁ * 1) : Q ⊕ ↥N) = Sum.inr (n₂ * 1) :=
    congrFun h (Sum.inr (1 : ↥N))
  rw [mul_one, mul_one] at h2
  exact Sum.inr_injective h2

/-- **The decoding surjection of the main decomposition.** For
$\mathrm{act} \colon M \to^* \mathrm{End}(Q)$, $c \in M$, and a submonoid $N \le M$, the map
$\varphi \colon cQ \times (Q \sqcup N) \to Q$ defined by $\varphi(p, \mathrm{inl}\,q) = q$ and
$\varphi(p, \mathrm{inr}\,n) = \mathrm{act}(n)(p)$ (the value of the local state $p \in cQ$,
transported by $n$). This is the cover decoding of DKS Thm 3.1. -/
def dksProj {M Q : Type} [Monoid M] (act : M →* Function.End Q) (c : M)
    (N : Submonoid M) : cQSet act c × (Q ⊕ ↥N) → Q :=
  fun s => Sum.elim (fun q => q) (fun n : ↥N => act n.1 s.1.1) s.2

/-- **The decoding map is surjective.** If $Q$ is nonempty, the decoding map `dksProj` is
surjective: every $q \in Q$ is $\varphi(p_0, \mathrm{inl}\,q)$ for any point $p_0$ of the image
state set $cQ$ — which is nonempty because $\mathrm{act}(c)(q_0) \in cQ$ for any $q_0 \in Q$.
(The empty/subsingleton $Q$ case never reaches this lemma: the induction `dks_aux` dispatches it
to the empty tower first.)

*Proof sketch.* As stated: $cQ$ is inhabited by $\langle \mathrm{act}(c)(q_0), q_0 \rangle$ for
$q_0$ from `Nonempty` $Q$, and $\varphi(p_0, \mathrm{inl}\,q) = q$. -/
lemma dks_proj_surjective {M Q : Type} [Monoid M] [Nonempty Q]
    (act : M →* Function.End Q) (c : M) (N : Submonoid M) :
    Function.Surjective (dksProj act c N) := by
  intro q
  obtain ⟨q₀⟩ := ‹Nonempty Q›
  exact ⟨(⟨act c q₀, q₀, rfl⟩, Sum.inl q), rfl⟩

/-- **Cover family 1: constants are covered.** In the wreath product
$\overline{(cQ, M_c)} \wr_{Q \sqcup N} \overline{(Q \sqcup N, N)}$ — decoration the constants
closure `closureMonoid` of the local action `localActHom`, base the constants closure of the
extension action `extAct`, both acting by evaluation — every constant transformation
$\overline{x} \in \mathrm{End}(Q)$, $x \in Q$, is covered (`Covers`) with respect to the decoding
`dksProj`. (DKS Thm 3.1, first cover family.)

*Proof sketch.* Take $\hat{w} := (\lambda y.\,1,\ \overline{\mathrm{inl}\,x})$ — trivial
decoration, base the constant onto $\mathrm{inl}\,x$, which lies in the base closure because
constants are generators. Then $\hat{w} \bullet (p, y) = (p, \mathrm{inl}\,x)$, so
$\varphi(\hat{w} \bullet (p,y)) = x = \overline{x}(\varphi(p,y))$. Direct computation. -/
lemma cover_const_end {M Q : Type} [Monoid M] (act : M →* Function.End Q) (c : M)
    (N : Submonoid M) (x : Q) :
    ∃ w : WreathProduct ↥(closureMonoid (localActHom act c))
      ↥(closureMonoid (extAct act N)) (Q ⊕ ↥N),
      Covers (dksProj act c N) w (constEnd x) := by
  refine ⟨⟨fun _ => 1, ⟨constEnd (Sum.inl x),
    Submonoid.subset_closure (Set.mem_union_right _ ⟨Sum.inl x, rfl⟩)⟩⟩, ?_⟩
  intro p y
  rfl

/-- **Cover family 2: the action of a submonoid element is covered.** In the wreath product of
`cover_const_end`, for every $n \in N$ the transformation $\mathrm{act}(n) \in \mathrm{End}(Q)$
is covered (`Covers`) with respect to the decoding `dksProj`. (DKS Thm 3.1, second cover family —
their $k_c$ with identity decoration.)

*Proof sketch.* Take $\hat{w} := (\lambda y.\,1,\ \mathrm{extAct}(n))$ — trivial decoration, base
the extension action of $n$ (a generator of the base closure). On $(p, \mathrm{inl}\,q)$:
$\hat{w} \bullet (p, \mathrm{inl}\,q) = (p, \mathrm{inl}\,(\mathrm{act}(n)(q)))$, and
$\varphi = \mathrm{act}(n)(q) = \mathrm{act}(n)(\varphi(p, \mathrm{inl}\,q))$. On
$(p, \mathrm{inr}\,m)$: $\hat{w} \bullet (p, \mathrm{inr}\,m) = (p, \mathrm{inr}\,(n m))$, and
$\varphi = \mathrm{act}(nm)(p) = \mathrm{act}(n)(\mathrm{act}(m)(p)) = \mathrm{act}(n)(\varphi(p,
\mathrm{inr}\,m))$ by multiplicativity. Direct computation. -/
lemma cover_act_of_mem {M Q : Type} [Monoid M] (act : M →* Function.End Q) (c : M)
    (N : Submonoid M) (n : ↥N) :
    ∃ w : WreathProduct ↥(closureMonoid (localActHom act c))
      ↥(closureMonoid (extAct act N)) (Q ⊕ ↥N),
      Covers (dksProj act c N) w (act n.1) := by
  refine ⟨⟨fun _ => 1, ⟨extAct act N n,
    Submonoid.subset_closure (Set.mem_union_left _ ⟨n, rfl⟩)⟩⟩, ?_⟩
  intro p y
  cases y with
  | inl q => rfl
  | inr m =>
      change act ((n * m : ↥N) : M) p.1 = act (n : M) (act (m : M) p.1)
      rw [MulMemClass.coe_mul, map_mul]
      rfl

/-- **Cover family 3: the action of the chosen non-unit is covered.** In the wreath product of
`cover_const_end`, the transformation $\mathrm{act}(c) \in \mathrm{End}(Q)$ itself is covered
(`Covers`) with respect to the decoding `dksProj`. This is THE local-divisor step of DKS Thm 3.1
(their decoration $f_c$ with $y f_c = \overline{y \cdot c}$ on states and $n f_c = cnc$ on $N$,
base constant onto $1 \in N$).

*Proof sketch.* Take $\hat{w} := (f_c,\ \overline{\mathrm{inr}\,1})$ with decoration
$f_c(\mathrm{inl}\,q) := \overline{\langle \mathrm{act}(c)(q) \rangle}$ (a constant of
$\mathrm{End}(cQ)$, hence in the decoration closure) and
$f_c(\mathrm{inr}\,n) := \mathrm{localActHom}\,\langle c n c \rangle$ (in the range of the local
action, hence in the decoration closure; $cnc \in cM \cap Mc$ with the two evident factorizations
$cnc = c \cdot (nc) = (cn) \cdot c$). Then
$\hat{w} \bullet (p, y) = (f_c(y) \bullet p,\ \mathrm{inr}\,1)$, so
$\varphi(\hat{w} \bullet (p,y)) = \mathrm{act}(1)$ applied to the underlying value of
$f_c(y) \bullet p$ — which is that value itself. For $y = \mathrm{inl}\,q$: the value is
$\mathrm{act}(c)(q) = \mathrm{act}(c)(\varphi(p, \mathrm{inl}\,q))$. For $y = \mathrm{inr}\,n$
and $p = \mathrm{act}(c)(x)$: writing $cnc = b'c$ for the chosen right factorization baked into
`localActHom`, the value is $\mathrm{act}(b')(p) = \mathrm{act}(b'c)(x) = \mathrm{act}(cnc)(x) =
\mathrm{act}(c)(\mathrm{act}(n)(\mathrm{act}(c)(x))) = \mathrm{act}(c)(\varphi(p,
\mathrm{inr}\,n))$ — the chosen $b'$ drops out because the displayed value $\mathrm{act}(cnc)(x)$
is determined by $cnc$ alone. Direct computation. -/
lemma cover_act_c {M Q : Type} [Monoid M] (act : M →* Function.End Q) (c : M)
    (N : Submonoid M) :
    ∃ w : WreathProduct ↥(closureMonoid (localActHom act c))
      ↥(closureMonoid (extAct act N)) (Q ⊕ ↥N),
      Covers (dksProj act c N) w (act c) := by
  -- The DKS family-3 witness: the decoration `f_c` sends a state `inl q` to the constant
  -- transformation of `cQ` onto `⟨act c q⟩`, and `inr n` to the local action of
  -- `c·n·c ∈ cM ∩ Mc`; the base is the constant onto `inr 1`.
  refine ⟨⟨Sum.elim
      (fun q => ⟨constEnd ⟨act c q, q, rfl⟩,
        Submonoid.subset_closure (Set.mem_union_right _ ⟨_, rfl⟩)⟩)
      (fun n => ⟨localActHom act c ⟨c * n.1 * c, ⟨n.1 * c, mul_assoc c n.1 c⟩, ⟨c * n.1, rfl⟩⟩,
        Submonoid.subset_closure (Set.mem_union_left _ ⟨_, rfl⟩)⟩),
      ⟨constEnd (Sum.inr 1),
        Submonoid.subset_closure (Set.mem_union_right _ ⟨_, rfl⟩)⟩⟩, ?_⟩
  -- After the constant base, the second coordinate is `inr 1`, so the decoded value is
  -- `act 1` of the new local state's value — i.e. that value itself:
  have hone : ∀ z : Q, act ((1 : ↥N) : M) z = z := by
    intro z
    rw [OneMemClass.coe_one, map_one]
    rfl
  -- The local-divisor computation: for `u ∈ cM ∩ Mc` with `u = c·m·c` and a local state
  -- `p = act c x`, the chosen-factorization action value is `act c (act m p)` — the
  -- choice drops out because the value equals `act (c·m·c) x`:
  have key : ∀ (u : LocalDivisor M c) (m : M), u.val = c * m * c →
      ∀ p : cQSet act c, act (Classical.choose u.mem_right) p.1 = act c (act m p.1) := by
    intro u m hu p
    obtain ⟨x, hx⟩ := p.2
    have hb := Classical.choose_spec u.mem_right
    rw [hx]
    calc act (Classical.choose u.mem_right) (act c x)
        = act (Classical.choose u.mem_right * c) x := by rw [map_mul]; rfl
      _ = act u.val x := by rw [← hb]
      _ = act (c * m * c) x := by rw [hu]
      _ = act c (act m (act c x)) := by rw [map_mul, map_mul]; rfl
  intro p y
  cases y with
  | inl q => exact hone (act c q)
  | inr n =>
      exact (hone _).trans
        (key ⟨c * n.1 * c, ⟨n.1 * c, mul_assoc c n.1 c⟩, ⟨c * n.1, rfl⟩⟩ n.1 rfl p)

/-- **Main decomposition: the closure divides local-divisor wreath extension.** Let $M$ be a
monoid with decidable equality, $Q$ a nonempty type,
$\mathrm{act} \colon M \to^* \mathrm{End}(Q)$, $A$ a finite generating set of $M$
($\texttt{Submonoid.closure}\,A = \top$), $c \in M$, and $N \le M$ a submonoid containing
$A \setminus \{c\}$. Then the constants closure $\overline{(Q, M)}$ (`closureMonoid`) divides, as
a semigroup, the wreath product
$\overline{(cQ, M_c)} \wr_{Q \sqcup N} \overline{(Q \sqcup N, N)}$ of `cover_const_end`. This is
DKS Theorem 3.1; $c \in A$ is not needed (if $c \notin A$, family 3 is simply unused). No
injectivity of $\mathrm{act}$ is needed here.

*Proof sketch.* Apply `sgdiv_of_covering` with the decoding $\varphi$ of `dksProj` — surjective
by `dks_proj_surjective` ($Q$ nonempty) — and the generating set
$\mathrm{act}(A) \cup \{\overline{x}\}$ of the closure, which generates by `closure_monoid_gen`
at the hypothesis $\langle A \rangle = \top$. Coverage of the generators: constants
$\overline{x}$ by `cover_const_end`; $\mathrm{act}(a)$ for $a \in A$, $a \ne c$ by
`cover_act_of_mem` applied at the member of $N$ that the containment hypothesis produces from
$a$; and $\mathrm{act}(c)$ by `cover_act_c`. -/
lemma main_decomposition {M Q : Type} [Monoid M] [DecidableEq M] [Nonempty Q]
    (act : M →* Function.End Q) (A : Finset M)
    (_hA : Submonoid.closure (A : Set M) = ⊤) (c : M) (N : Submonoid M)
    (_hN : ((A.erase c : Finset M) : Set M) ⊆ (N : Set M)) :
    SgDiv ↥(closureMonoid act)
      (WreathProduct ↥(closureMonoid (localActHom act c))
        ↥(closureMonoid (extAct act N)) (Q ⊕ ↥N)) := by
  -- Division from covering, at the decoding `dksProj` (surjective since `Q` is nonempty)
  -- and the generating set `act '' A ∪ {constants}` of the closure (`closure_monoid_gen`
  -- at the generation hypothesis `_hA`):
  refine sgdiv_of_covering (dks_proj_surjective act c N)
    ((⇑act) '' (A : Set M) ∪ Set.range (constEnd : Q → Function.End Q))
    (closureMonoid act) (closure_monoid_gen act (A : Set M) _hA) ?_
  rintro t (⟨a, ha, rfl⟩ | ⟨x, rfl⟩)
  · -- Generators `act a`, `a ∈ A`: family 3 covers the chosen `c`, family 2 covers the
    -- members of `N` — and `a ≠ c` lands in `N` through the containment `_hN`.
    by_cases hac : a = c
    · rw [hac]
      exact cover_act_c act c N
    · exact cover_act_of_mem act c N
        ⟨a, _hN (Finset.mem_coe.mpr (Finset.mem_erase.mpr ⟨hac, Finset.mem_coe.mp ha⟩))⟩
  · -- Constant generators: family 1.
    exact cover_const_end act c N x

/-! ## The group case (DKS Lemma 2.9) -/

/-- **The decoding surjection of the group case.** For a group $G$ and a monoid homomorphism
$\mathrm{act} \colon G \to^* \mathrm{End}(Q)$, the map $\varphi \colon Q \times G \to Q$,
$\varphi(q, g) = \mathrm{act}(g)(q)$. It is surjective since $\varphi(q, 1) = q$. This is the
decoding of DKS Lemma 2.9. -/
def groupProj {G Q : Type} [Group G] (act : G →* Function.End Q) : Q × G → Q :=
  fun s => act s.2 s.1

/-- **Group-case cover family 1: group translations are covered.** In the wreath product
$U(Q) \wr_G G$ — decoration the reset submonoid `resetSubmonoid` acting on $Q$ by evaluation,
base $G$ acting on itself by left multiplication — every $\mathrm{act}(g) \in \mathrm{End}(Q)$,
$g \in G$, is covered (`Covers`) with respect to the decoding `groupProj`. (DKS Lemma 2.9,
appendix, cover $(k_1, g)$.)

*Proof sketch.* Take $\hat{w} := (\lambda m.\,1,\ g)$ (trivial decoration, base $g$). Then
$\hat{w} \bullet (q, m) = (q, g m)$ and $\varphi = \mathrm{act}(gm)(q) =
\mathrm{act}(g)(\mathrm{act}(m)(q)) = \mathrm{act}(g)(\varphi(q,m))$ by multiplicativity. Direct
computation. -/
lemma cover_act_group {G Q : Type} [Group G] (act : G →* Function.End Q) (g : G) :
    ∃ w : WreathProduct ↥(resetSubmonoid Q) G G,
      Covers (groupProj act) w (act g) := by
  -- The DKS family-1 witness: trivial decoration, base `g`. Then
  -- `ŵ • (p, y) = (p, g·y)` decodes to `act (g·y) p = act g (act y p)` by
  -- multiplicativity of `act` (composition in `Function.End` is definitional).
  refine ⟨⟨fun _ => 1, g⟩, fun p y => ?_⟩
  simp only [groupProj, one_smul, smul_eq_mul, map_mul]
  rfl

/-- **Group-case cover family 2: constants are covered (uses inverses).** In the wreath product
of `cover_act_group`, every constant $\overline{x} \in \mathrm{End}(Q)$, $x \in Q$, is covered
(`Covers`) with respect to the decoding `groupProj`. This is the only place in the whole
construction where invertibility is used (DKS Lemma 2.9, appendix, cover $(f_x, 1)$ with
$h f_x = x \cdot h^{-1}$, adapted to left actions).

*Proof sketch.* Take $\hat{w} := (f_x, 1)$ with decoration
$f_x(m) := \overline{\, \mathrm{act}(m^{-1})(x)\,}$ (a constant of $\mathrm{End}(Q)$, hence in
the reset submonoid). Then $\hat{w} \bullet (q, m) = (\mathrm{act}(m^{-1})(x),\ m)$ and $\varphi
= \mathrm{act}(m)(\mathrm{act}(m^{-1})(x)) = \mathrm{act}(m m^{-1})(x) = x =
\overline{x}(\varphi(q,m))$ — the group inverse cancels. Direct computation. -/
lemma cover_const_group {G Q : Type} [Group G] (act : G →* Function.End Q) (x : Q) :
    ∃ w : WreathProduct ↥(resetSubmonoid Q) G G,
      Covers (groupProj act) w (constEnd x) := by
  -- The DKS family-2 witness: decoration `f_x(m) := constEnd (act m⁻¹ x)` — a constant of
  -- `End Q`, hence a generator of the reset submonoid — and trivial base.
  refine ⟨⟨fun m => ⟨constEnd (act m⁻¹ x), Submonoid.subset_closure ⟨act m⁻¹ x, rfl⟩⟩, 1⟩, ?_⟩
  intro p y
  -- Up to definitional unfolding the cover equation reads `act (1 * y) (act y⁻¹ x) = x`;
  -- the group inverse cancels through multiplicativity:
  have key : act ((1 : G) * y) (act y⁻¹ x) = x := by
    calc act ((1 : G) * y) (act y⁻¹ x)
        = act (y * y⁻¹) x := by rw [one_mul, map_mul]; rfl
      _ = x := by rw [mul_inv_cancel, map_one]; rfl
  exact key

/-- **Group case: the closure of a group representation divides resets wreath G.** Let $G$ be a
group and $\mathrm{act} \colon G \to^* \mathrm{End}(Q)$ a monoid homomorphism (no faithfulness
needed). Then the constants closure $\overline{(Q, G)}$ (`closureMonoid`) divides, as a
semigroup, the wreath product $U(Q) \wr_G G$ of `cover_act_group` (reset decoration over the left
regular base). This is DKS Lemma 2.9.

*Proof sketch.* Apply `sgdiv_of_covering` with the decoding `groupProj`, surjective because
$\varphi(q, 1) = \mathrm{act}(1)(q) = q$, and the DEFINING generating set
$\mathrm{range}(\mathrm{act}) \cup \{\overline{x}\}$ of the closure (`closureMonoid` is literally
the closure of this set, so the generation hypothesis is definitional and no generating-set
transport is needed). Coverage: $\mathrm{act}(g)$ by `cover_act_group`; constants by
`cover_const_group`. -/
lemma group_decomposition {G Q : Type} [Group G] (act : G →* Function.End Q) :
    SgDiv ↥(closureMonoid act) (WreathProduct ↥(resetSubmonoid Q) G G) := by
  -- The decoding `groupProj` is surjective: `φ (q, 1) = act 1 q = q`.
  have hφ : Function.Surjective (groupProj act) := fun q =>
    ⟨(q, 1), by simp only [groupProj, map_one]; rfl⟩
  -- Division from covering at the DEFINING generating set of the closure
  -- (`closureMonoid act` is literally the closure of `range act ∪ range constEnd`,
  -- so the generation hypothesis is `rfl`):
  refine sgdiv_of_covering hφ
    (Set.range (⇑act) ∪ Set.range (constEnd : Q → Function.End Q))
    (closureMonoid act) rfl ?_
  rintro t (⟨g, rfl⟩ | ⟨x, rfl⟩)
  · -- Group translations: family 1.
    exact cover_act_group act g
  · -- Constants: family 2.
    exact cover_const_group act x

/-! ## The induction on `|M|` (DKS Corollary 3.2) -/

/-- **A submonoid divides its ambient monoid.** For every submonoid $N$ of a monoid $M$, the
subtype monoid $N$ divides $M$ in the sense of `MonoidDivides` (a
surjective monoid homomorphism from a submonoid of $M$ onto $N$). Used by `dks_aux` to transport
the simple-group divisibility guarantee from the recursive base factor $(Q \sqcup N, N)$ up to
$M$.

*Proof sketch.* Witness: the submonoid $N$ itself with the identity homomorphism, which is
surjective onto the subtype. -/
lemma submonoid_divides {M : Type} [Monoid M] (N : Submonoid M) :
    KrohnRhodes.MonoidDivides ↥N M := by
  exact ⟨N, MonoidHom.id ↥N, Function.surjective_id⟩

/-- **Every finite monoid has a minimal finite generating set.** Every finite monoid $M$ (with
decidable equality) has a finite generating set $A$ ($\texttt{Submonoid.closure}\,A = \top$) that
is $\subseteq$-minimal in the strong sense that no single generator can be dropped: for every
$a \in A$, $\texttt{Submonoid.closure}\,(A \setminus \{a\}) \ne \top$. (Folklore.)

*Proof sketch.* $\texttt{Finset.univ}$ generates ($1$ and all of $M$ are in the closure). Among
all generating finsets pick one of minimal cardinality (strong induction on `Finset.card`, or
well-foundedness of $<$ on $\mathbb{N}$): if some $a \in A$ could be dropped with
$\langle A \setminus \{a\} \rangle = \top$, the erased set would be a strictly smaller generating
finset, contradicting minimality. -/
lemma exists_minimal_generating (M : Type) [Monoid M] [Finite M] [DecidableEq M] :
    ∃ A : Finset M, Submonoid.closure (A : Set M) = ⊤ ∧
      ∀ a ∈ A, Submonoid.closure ((A.erase a : Finset M) : Set M) ≠ ⊤ := by
  classical
  cases nonempty_fintype M
  have hex : ∃ n : ℕ, ∃ A : Finset M, A.card = n ∧ Submonoid.closure (A : Set M) = ⊤ :=
    ⟨(Finset.univ : Finset M).card, Finset.univ, rfl, by
      rw [Finset.coe_univ, Submonoid.closure_univ]⟩
  obtain ⟨A, hcard, hA⟩ := Nat.find_spec hex
  refine ⟨A, hA, fun a ha hcl => ?_⟩
  have hlt : (A.erase a).card < Nat.find hex := by
    rw [← hcard]; exact Finset.card_erase_lt_of_mem ha
  exact Nat.find_min hex hlt ⟨A.erase a, rfl, hcl⟩

/-- **A non-group monoid has a non-unit in every generating set.** Let $M$ be a monoid, $A$ a
finite generating set ($\texttt{Submonoid.closure}\,A = \top$), and suppose $M$ is not a group:
some $m \in M$ is not a unit. Then some $c \in A$ is not a unit. (Folklore.)

*Proof sketch.* Contrapositive: if every element of $A$ is a unit, then every element of the
closure is a unit, by `Submonoid.closure_induction` — $1$ is a unit and units are closed under
multiplication (`IsUnit.mul`); since the closure is all of $M$, this contradicts the non-unit
$m$. -/
lemma exists_nonunit_generator {M : Type} [Monoid M] {A : Finset M}
    (hA : Submonoid.closure (A : Set M) = ⊤) (hM : ∃ m : M, ¬ IsUnit m) :
    ∃ c ∈ A, ¬ IsUnit c := by
  by_contra h
  push_neg at h
  obtain ⟨m, hm⟩ := hM
  refine hm ?_
  clear hm
  have hmem : m ∈ Submonoid.closure (A : Set M) := by
    rw [hA]; exact Submonoid.mem_top m
  induction hmem using Submonoid.closure_induction with
  | mem x hx => exact h x hx
  | one => exact isUnit_one
  | mul x y hx hy ihx ihy => exact ihx.mul ihy

/-- **A proper submonoid of a finite monoid is strictly smaller.** For a finite monoid $M$ and a
submonoid $N \ne \top$, $\mathrm{Nat.card}\,N < \mathrm{Nat.card}\,M$. Applied by `dks_aux` to
$N = \langle A \setminus \{c\} \rangle$, proper by the minimality clause of
`exists_minimal_generating`, to make the second recursive call decrease.

*Proof sketch.* $N \ne \top$ makes the carrier set of $N$ a *proper* subset of the universe set
of $M$ (`Set.ssubset_univ_iff`; carrier-set equality converts back to $N = \top$ via
`SetLike.coe_set_eq` and `Submonoid.coe_top`). A proper subset of a finite set has strictly
smaller cardinality (`Set.Finite.card_lt_card` at `Set.finite_univ`), and `Nat.card_univ`
identifies $\mathrm{Nat.card}\,(\mathrm{Set.univ})$ with $\mathrm{Nat.card}\,M$. -/
lemma card_lt_of_proper {M : Type} [Monoid M] [Finite M] {N : Submonoid M}
    (hN : N ≠ ⊤) : Nat.card ↥N < Nat.card M := by
  have hssub : (N : Set M) ⊂ Set.univ :=
    Set.ssubset_univ_iff.mpr fun h =>
      hN (SetLike.coe_set_eq.mp (h.trans Submonoid.coe_top.symm))
  have hlt := Set.Finite.card_lt_card Set.finite_univ hssub
  rwa [Nat.card_univ] at hlt

/-- **Group dispatch: the closure tower for an all-units monoid.** Let $Q$ be a finite type, $M$
a finite monoid all of whose elements are units, and
$\mathrm{act} \colon M \to^* \mathrm{End}(Q)$ a monoid homomorphism. Then there is a factor list
(`KRFactor` atoms at universe $0$) whose iterated wreath product the constants closure
$\overline{(Q,M)}$ (`closureMonoid`) divides (`DivTowerWreath`), with every simple-group factor
dividing $M$ (`MonoidDivides`). The aperiodic factors — here a single
reset atom — are unconstrained. (DKS Cor 3.2, group case = Lemma 2.9 + Cor 2.8; Cor 2.8 is
replaced here by `group_subquotient_faithful_aux`, whose tower has all factors dividing the
group.)

*Proof sketch.* Endow $M$ with its group structure (`groupOfIsUnit`, definitionally extending the
given monoid). `group_decomposition` gives $\overline{(Q,M)} \preceq U(Q) \wr_M M$. The
decoration contributes the single aperiodic factor $\texttt{KRFactor.ofAperiodic}$ of the reset
submonoid — genuinely aperiodic by `reset_submonoid_aperiodic` — with its one-rung tower
(`divTowerWreath_ofAperiodic`). The base $M$ has the group tower
`group_subquotient_faithful_aux` (at $n = \mathrm{Nat.card}\,M$), whose `factorsDivide`
field already gives every factor (in particular every simple-group factor) dividing $M$. Assemble
with `divTowerWreath_wreathStep`: factors $:=$ reset atom $::$ group tower; the simple-group
factors all sit in the tail. -/
lemma dks_aux_group {Q M : Type} [Fintype Q] [Monoid M] [Finite M]
    (act : M →* Function.End Q) (_hU : ∀ m : M, IsUnit m) :
    ∃ factors : List KRFactor.{0}, DivTowerWreath ↥(closureMonoid act) factors ∧
      ∀ F ∈ factors, F.kind = KRFactorKind.simpleGroup →
        KrohnRhodes.MonoidDivides F.carrier M := by
  classical
  -- Endow `M` with its group structure (definitionally extending the given monoid).
  letI : Group M := groupOfIsUnit _hU
  haveI : Fintype M := Fintype.ofFinite M
  -- The group-case decomposition: the closure divides `U(Q) ≀_M M`.
  have hdec : SgDiv ↥(closureMonoid act) (WreathProduct ↥(resetSubmonoid Q) M M) :=
    group_decomposition act
  -- The base tower: the subquotient-faithful group tower for `M`, every factor
  -- (in particular every simple-group factor) dividing `M`.
  obtain ⟨towB⟩ := KrohnRhodes.group_subquotient_faithful_aux (Nat.card M) M le_rfl
  -- Assemble: factors := reset atom :: group tower.
  refine ⟨KRFactor.ofAperiodic ↥(resetSubmonoid Q) (reset_submonoid_aperiodic Q)
      :: towB.factors, ?_, ?_⟩
  · -- `divTowerWreath_wreathStep` concatenates the one-rung reset tower with the
    -- group tower along the division `hdec`.
    exact divTowerWreath_wreathStep
      [KRFactor.ofAperiodic ↥(resetSubmonoid Q) (reset_submonoid_aperiodic Q)]
      hdec (divTowerWreath_ofAperiodic _ (reset_submonoid_aperiodic Q)) towB.divides
  · -- The head atom is aperiodic-flagged (kind mismatch is impossible); the tail's
    -- simple-group factors divide `M` by the tower's `factorsDivide` field.
    intro F hF hk
    rcases List.mem_cons.mp hF with rfl | hF'
    · simp at hk
    · exact towB.factorsDivide F hF'

/-- **The DKS induction: closure towers with group factors dividing M.** For every $n$, every
finite type $Q$, every finite monoid $M$ with $\mathrm{Nat.card}\,M \le n$, and every INJECTIVE
monoid homomorphism $\mathrm{act} \colon M \to^* \mathrm{End}(Q)$: there is a factor list whose
iterated wreath product the constants closure $\overline{(Q,M)}$ (`closureMonoid`) divides
(`DivTowerWreath`), with every simple-group factor dividing $M$. The motive is stated over
closures, as in DKS, so that both recursive calls return exactly the decoration and base of the
main decomposition; the induction is on the monoid size only, never the state set (DKS Cor 3.2).

*Proof sketch.* Induction on the bound $n$ (the `Nat.rec` pattern of
`group_subquotient_faithful_aux`); the base $n = 0$ is vacuous, since a finite monoid is
nonempty and so has positive cardinality. DEGENERATE CASE ($Q$ subsingleton, covering
$Q = \emptyset$ and $|Q| = 1$): $\mathrm{End}(Q)$ is a subsingleton, hence so is the closure, and
the empty tower works (`divTowerWreath_nil_of_subsingleton`); the divisibility condition is
vacuous. GROUP CASE (every element a unit): `dks_aux_group`. NON-GROUP CASE ($Q$ nontrivial,
hence nonempty; some non-unit exists): choose a minimal generating finset $A$ by
`exists_minimal_generating` and a non-unit $c \in A$ by `exists_nonunit_generator`; set
$N := \langle A \setminus \{c\} \rangle$, proper by minimality, so
$\mathrm{Nat.card}\,N < \mathrm{Nat.card}\,M$ by `card_lt_of_proper`; also
$\mathrm{Nat.card}\,M_c < \mathrm{Nat.card}\,M$ by `local_divisor_card_lt`. Apply the inductive
hypothesis twice: at $(cQ,\ M_c,\ \mathrm{localActHom})$ — injective by `local_act_injective`
(here the faithfulness hypothesis is consumed), the $cQ$ Fintype instance by `Fintype.ofFinite` —
yielding a tower for the decoration closure with simple-group factors dividing $M_c$, hence
dividing $M$ through `LocalDivisor.localDivides` and `MonoidDivides.trans`; and at
$(Q \sqcup N,\ N,\ \mathrm{extAct})$ — injective by `ext_act_injective` — yielding a tower for
the base closure with simple-group factors dividing $N$, hence dividing $M$ through
`submonoid_divides` and `MonoidDivides.trans`. `main_decomposition` (at the containment
$A \setminus \{c\} \subseteq N$ by `Submonoid.subset_closure`) gives
$\overline{(Q,M)} \preceq \overline{(cQ, M_c)} \wr \overline{(Q \sqcup N, N)}$, and
`divTowerWreath_wreathStep` concatenates the two towers: factors $:=$ decoration tower $++$ base
tower. -/
lemma dks_aux (n : ℕ) :
    ∀ (Q : Type) [Fintype Q] (M : Type) [Monoid M] [Finite M]
      (act : M →* Function.End Q),
      Function.Injective act → Nat.card M ≤ n →
      ∃ factors : List KRFactor.{0}, DivTowerWreath ↥(closureMonoid act) factors ∧
        ∀ F ∈ factors, F.kind = KRFactorKind.simpleGroup →
          KrohnRhodes.MonoidDivides F.carrier M := by
  classical
  induction n with
  | zero =>
    -- `Nat.card M ≤ 0` is impossible: a finite monoid is nonempty, so its card is positive.
    intro Q _ M _ _ act _ hcard
    have : 0 < Nat.card M := Nat.card_pos
    omega
  | succ k IH =>
    intro Q _ M _ _ act hf hcard
    -- DEGENERATE CASE: `Q` subsingleton (covers `Q = ∅` and `|Q| = 1`). Then `End Q` is a
    -- subsingleton, hence so is the closure, and the empty tower works; the divisibility
    -- condition is vacuous.
    by_cases hQ : Subsingleton Q
    · haveI : Subsingleton (Function.End Q) := inferInstanceAs (Subsingleton (Q → Q))
      haveI : Subsingleton ↥(closureMonoid act) :=
        ⟨fun a b => Subtype.ext (Subsingleton.elim _ _)⟩
      exact ⟨[], divTowerWreath_nil_of_subsingleton _, by simp⟩
    -- `Q` nontrivial, hence nonempty.
    haveI : Nontrivial Q := not_subsingleton_iff_nontrivial.mp hQ
    -- GROUP CASE: every element a unit.
    by_cases hU : ∀ m : M, IsUnit m
    · exact dks_aux_group act hU
    -- NON-GROUP CASE: some non-unit exists.
    push_neg at hU
    -- Choose a minimal generating finset `A` and a non-unit `c ∈ A`; set
    -- `N := ⟨A \ {c}⟩`, proper by minimality.
    obtain ⟨A, hA, hmin⟩ := exists_minimal_generating M
    obtain ⟨c, hcA, hc⟩ := exists_nonunit_generator hA hU
    set N : Submonoid M := Submonoid.closure ((A.erase c : Finset M) : Set M) with hNdef
    have hNtop : N ≠ ⊤ := hmin c hcA
    -- Instances for the two recursive calls (`Fintype.ofFinite`).
    haveI : Finite (cQSet act c) :=
      inferInstanceAs (Finite {q : Q // ∃ x : Q, q = act c x})
    haveI : Fintype (cQSet act c) := Fintype.ofFinite _
    haveI : Fintype ↥N := Fintype.ofFinite _
    -- First recursive call, at `(cQ, M_c, localActHom)`: the decoration tower, with
    -- simple-group factors dividing `M_c`. Decrease: `|M_c| < |M| ≤ k + 1`.
    have hcardc : Nat.card (LocalDivisor M c) ≤ k :=
      Nat.lt_succ_iff.mp (lt_of_lt_of_le (local_divisor_card_lt hc) hcard)
    obtain ⟨factorsD, towD, hD⟩ := IH (cQSet act c) (LocalDivisor M c)
      (localActHom act c) (local_act_injective act c hf) hcardc
    -- Second recursive call, at `(Q ⊔ N, N, extAct)`: the base tower, with simple-group
    -- factors dividing `N`. Decrease: `|N| < |M| ≤ k + 1` since `N` is proper.
    have hcardN : Nat.card ↥N ≤ k :=
      Nat.lt_succ_iff.mp (lt_of_lt_of_le (card_lt_of_proper hNtop) hcard)
    obtain ⟨factorsB, towB, hB⟩ := IH (Q ⊕ ↥N) ↥N (extAct act N)
      (ext_act_injective act N) hcardN
    -- The main decomposition: the closure divides the wreath of the two recursive
    -- closures (at the containment `A \ {c} ⊆ N`).
    have hdec := main_decomposition act A hA c N Submonoid.subset_closure
    -- Assemble: factors := decoration tower ++ base tower.
    refine ⟨factorsD ++ factorsB,
      divTowerWreath_wreathStep factorsD hdec towD towB, ?_⟩
    -- Simple-group divisibility into `M`: through `M_c ÷ M` (`LocalDivisor.localDivides`)
    -- on the decoration side, and `N ÷ M` on the base side.
    intro F hF hk
    rcases List.mem_append.mp hF with hFD | hFB
    · exact (hD F hFD hk).trans LocalDivisor.localDivides
    · exact (hB F hFB hk).trans (submonoid_divides N)

/-! ## The main theorem (DKS Cor 3.2 + Thm 4.1) -/

/-- **The Krohn-Rhodes factor tower with the prime-divisor guarantee.** For a finite monoid $M$:
a *Krohn-Rhodes factor tower with the prime-divisor guarantee* (Krohn-Rhodes 1965; DKS
arXiv:1111.1585 Thm 4.1) is a list of `KRFactor` atoms (each a finite monoid flagged and
witnessed as aperiodic or simple-group), together with (i) a proof `DivTowerWreath` $M$ `factors`
that $M$ divides the right-iterated wreath product of the list, and (ii) the guarantee that every
SIMPLE-GROUP factor divides $M$ (`MonoidDivides`). Aperiodic factors are
only required to be aperiodic. Stated at `Type` (universe $0$), with `KRFactor.{0}`. -/
structure KRFactorTowerGrp (M : Type) [Monoid M] [Finite M] where
  /-- The explicit list of Krohn-Rhodes prime factors. -/
  factors : List KRFactor.{0}
  /-- `M` divides the right-iterated wreath product of `factors`. -/
  divides : DivTowerWreath M factors
  /-- Every SIMPLE-GROUP factor divides `M` (the Krohn-Rhodes prime-divisor guarantee;
      aperiodic factors are only required to be aperiodic). -/
  groupFactorsDivide : ∀ F ∈ factors, F.kind = KRFactorKind.simpleGroup →
    KrohnRhodes.MonoidDivides F.carrier M

/-- **The Krohn-Rhodes prime decomposition theorem.** Every finite monoid $M$ admits a
Krohn-Rhodes factor tower with the prime-divisor guarantee (`KRFactorTowerGrp`): an explicit list
of aperiodic and simple-group atoms whose right-iterated wreath product $M$ divides, with every
simple-group factor dividing $M$ and the aperiodic factors only required to be aperiodic
(Krohn-Rhodes 1965; Diekert-Kufleitner-Steinberg arXiv:1111.1585 Theorem 4.1, via the
local-divisor proof of their Thm 3.1 + Cor 3.2). Stated for $M : \texttt{Type}$ (universe $0$).
No `[DecidableEq M]` hypothesis is needed; decidability is obtained classically inside the proof.

*Proof sketch.* Cayley + the closure induction (DKS Cor 3.2 + Thm 4.1). Set $Q := M$
(`Fintype.ofFinite`) with the left regular representation
$\mathrm{act} := \texttt{MulAction.toEndHom}$, injective by
`monoid_faithful_self`. `dks_aux` at $n := \mathrm{Nat.card}\,M$
yields a factor list, a tower for the constants closure $\overline{(M,M)}$, and the simple-group
divisibility into $M$. `sgdiv_closure_monoid` gives $M \preceq \overline{(M,M)}$, and
`divTowerWreath_of_sgDiv` transfers the tower from the closure to $M$; the `groupFactorsDivide`
field carries over unchanged. Package as `KRFactorTowerGrp`. -/
theorem krohn_rhodes_prime_decomposition (M : Type) [Monoid M] [Finite M] :
    Nonempty (KRFactorTowerGrp M) := by
  classical
  haveI : Fintype M := Fintype.ofFinite M
  -- Cayley: the left regular representation `M →* End M` is injective
  -- (`monoid_faithful_self`).
  have hf : Function.Injective (MulAction.toEndHom (M := M) (α := M)) :=
    KrohnRhodes.monoid_faithful_self M
  -- The DKS induction at `n := Nat.card M`: a factor list, a tower for the constants
  -- closure `(M,M)‾`, and the simple-group divisibility into `M`.
  obtain ⟨factors, towC, hdiv⟩ :=
    dks_aux (Nat.card M) M M (MulAction.toEndHom (M := M) (α := M)) hf le_rfl
  -- `M ≼ (M,M)‾` pulls the tower back to `M` (`divTowerWreath_of_sgDiv`);
  -- the `groupFactorsDivide` field carries over unchanged.
  exact ⟨⟨factors,
    divTowerWreath_of_sgDiv (sgdiv_closure_monoid _ hf) towC, hdiv⟩⟩

/-! ## A chosen factor tower -/

/-- **The chosen Krohn-Rhodes prime factor tower of a finite monoid.** For a finite monoid $M$, a
chosen factor tower with the prime-divisor guarantee (`KRFactorTowerGrp`), extracted from the
existence theorem `krohn_rhodes_prime_decomposition` by `Nonempty.some`. -/
noncomputable def krFactorTowerGrpOf (M : Type) [Monoid M] [Finite M] :
    KRFactorTowerGrp M :=
  (krohn_rhodes_prime_decomposition M).some

end KrohnRhodes
